# Generated by Django 3.0.4 on 2020-03-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20200305_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='bank_details_for_salary',
            new_name='bank_name_for_salary',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='userprofile',
            new_name='experience_documents',
        ),
        migrations.AddField(
            model_name='registration',
            name='account_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='designation',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='hobbies',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='profilepic',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='skills',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
