# Generated by Django 3.0.4 on 2020-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_auto_20200305_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='employee_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
