# Generated by Django 3.0.4 on 2020-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_registration_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addurl_project_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenantid', models.CharField(blank=True, max_length=250)),
                ('tenant_url', models.URLField(blank=True)),
            ],
        ),
    ]
