# Generated by Django 3.0.4 on 2020-03-05 17:52

import center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_auto_20200305_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addurl_project_model',
            name='tenant_url',
            field=models.CharField(max_length=250, validators=[center.models.OptionalSchemeURLValidator()]),
        ),
    ]
